name: 'faros-cicd-github-action'
description: 'Faros CI/CD Github Action'
author: 'Faros AI, Inc.'
inputs:
  api-key:
    required: true
    description: 'Faros API Key'
  event:
    required: true
    description: 'Which CI/CD event the data is for. Can be either CI or CD'
  run-status:
    required: true
    description: 'CI/CD build/deployment status'
  run-started-at:
    required: false
    description: 'CI/CD process start time'
  run-ended-at:
    required: false
    description: 'CI/CD process end time'
  artifact:
    required: false
    description: 'The URI of the artifact that was built or deployed'
  deploy:
    required: false
    description: 'The URI of the deployment. Required for CD events'
  deploy-status:
    required: false
    description: 'The status of the deployment. Required for CD events'
  deploy-app-platform:
    required: false
    description: 'The platform the application is being deployed on, e.g. ECS, K8s'
  deploy-started-at:
    required: false
    description: 'Deployment process start time'
  deploy-ended-at:
    required: false
    description: 'Deployment process end time'
  api-url:
    required: false
    description: 'Faros API URL, e.g. https://api.faros.ai'
  graph:
    required: false
    description: "Graph name to use when invoking Faros API. Uses 'default' graph if no name is provided"
branding:
  icon: fast-forward
  color: 'blue'
runs:
  using: 'node12'
  main: 'dist/index.js'
