name: 'faros-cicd-github-action'
description: 'Faros CI/CD Github Action'
author: 'Faros AI, Inc.'
inputs:
  api-url:
    required: true
    description: 'Faros API URL, e.g. https://api.faros.ai'
  api-key:
    required: true
    description: 'Faros API Key'
  model:
    required: true
    description: 'Which CI/CD model the data is for. Can be either build or deployment'
  started-at:
    required: true
    description: 'CI/CD process start time'
  status:
    required: true
    description: 'CI/CD job status'
  ended-at:
    required: false
    description: 'CI/CD process end time'
  deploy-id:
    required: false
    description: 'The deployment id of the deployment info from source service'
  deploy-platform:
    required: false
    description: 'The deployment platform such as CodeDeploy, Spinnaker'
  deploy-app-name:
    required: false
    description: 'The name of the application for deployment info'
  deploy-app-platform:
    required: false
    description: 'The platform application is being deployed to such as ECS/K8s'
  graph:
    required: false
    description: "Graph name to use when invoking Faros API. Uses 'default' graph if no name is provided"

runs:
  using: 'node12'
  main: 'dist/index.js'
